name: 🔨 build

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Set env as secret
        env:
          ENV_VAL: ${{ secrets.env }}
        run: |
          import os
          data = open(".env", "w")
          for q in (os.getenv("ENV_VAL")):
            data.write(q)
        shell: python
      - name: set next.config.js
        run: |
          mv next.config.js .next.config.js
          mv next.config.js.gh next.config.js

      - run: npm install
      - run: npm run build
      - run: npm run export

      - name: DeployGitHubPages
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./out
      - name: restore next.config.js
        run: |
          mv next.config.js next.config.js.gh 
          mv .next.config.js next.config.js 

      - run: npm install
      - run: npm run build
      - run: npm run export

      - name: DeployFirebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          steps:
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

